[package]
name = "planner"
version = "0.1.0"
edition = "2024"

[dependencies]
common = { path = "../common" }
parser = { path = "../parser" }
cmd = { path = "../cmd" }
tokenize = { path = "../tokenize" }
utils = { path = "../utils" }