[package]
name = "cmd"
version = "0.1.0"
edition = "2024"

[dependencies]
common = { path = "../common" }
utils = { path = "../utils" }
tokenize = { path = "../tokenize" }
datagramv2 = { path = "../datagramv2" }